### ISSUE TITLE
Flight level and workshop

### ISSUE THREAD

**Issue by tindolt** [ManuelSchmitz/SCAM#13]
Hey, have you asked cheerkin if you can upload an alt workshop for these updated versions?
Also have you fixed the issue of when a miner tries to return it does not respect terrain that is in the way. Today I tried to mine an ore location that was 1.5KM away and when the miner attempted to return it just didnt go up far enough and ended up smacking into the terrain.

**Comment by tindolt** [comment]
![image](https://github.com/ManuelSchmitz/SCAM/assets/122586790/e5e9d220-6829-4a3e-b004-78bc99687cb4)

**Comment by tindolt** [comment]
at run count 101 every time

**Comment by ManuelSchmitz** [comment]
Hello @tindolt , thanks for posting!

Yes, we have considered uploading the script to the workshop. We cannot just make an update to the existing WS item, because it is of type _Script_, and we have 2 scripts now. At some point, wel'll probably make a new WS item with type _Blueprint_. ... But first we have to fix some more problems.

Do you mean that the `getAbove-altitude` is not respected by the agents?

**Comment by tindolt** [comment]
You could upload two seperate script types one being dispatcher and one being worker agent.
I'm not sure I might be able to recreate the failure in a video of you want.
However I updated from the latest workshop version to your v10 beta and made sure I updated all parts correctly and now they error out on run count 101 with some big error, not sure where to get more logging into though, I have tried two different drone types both hydrogen, one of them was pro100's xu-3 and the other was cheerkin's h2 drone and they both ran into the same problem. I followed all the upgrading steps and it's not working for some reason, it's wanting some locks but then can't run it for some reason.

**Comment by ManuelSchmitz** [comment]
Apparently, we have 3 different problems here:

- Script publishing in WS: Let's skip this for now.

- Agent crashing into mountain.

- Dispatcher throwing exception after 101 ticks: This is the most important to me right now. Is that exception shown on your screenshot? At tick 100, the dispatcher starts granting airspace locks, because at that time all the handshaking with agents should be done. This problem is
  - An agent has requested a lock.
  - The requesting agent is not a subordinate of the dispatcher.
  - Any idea why that might be? Maybe you have a drone with an old script version somewhere around. If it is in antenna range, then it'll request airspace locks. Please check the log dispatcher's log for messages related to handshaking, especially those starting with `Ignoring handshake ...`.

Regardless, the crash _is_ a bug. The dispatcher is supposed to emit a warning message "Agent is no longer a subordinate", drop the request, and move on. Could you please try [this](https://github.com/ManuelSchmitz/SCAM/blob/fix_dispatcher_crash_at101/bin/script_dispatcher.cs) dispatcher script? It should fix the crash, at least.

**Comment by tindolt** [comment]
I will double check for old drones but that shouldn't make the whole entire system self destruct and hard lock.

**Comment by ManuelSchmitz** [comment]
Agreed. 
Please try the patch. It should make the dispatcher ignore the other agents.

**Comment by tindolt** [comment]
Ok, it's going to ignore outdated agents? Or should we make it so on init the agents have to be docked to the dispatchers grid?

**Comment by ManuelSchmitz** [comment]
Interesting idea, but it wouldn't work, unfortunately ...
Handshaking/pairing is done when the dispatcher script starts running. This also happens on world reload, when not all agents are docked. (e.g. in the middle of a task)

But I am trying to make the script more robust. It is the main focus of my work.

**Comment by tindolt** [comment]
![image](https://github.com/ManuelSchmitz/SCAM/assets/122586790/c388c6ff-e907-454c-8772-47c1dc4990ff)
Also when I run check code these come up but I assume it is a non issue.

**Comment by tindolt** [comment]
Let me know if there are any test cases you need me to run but I will try to get a video of the drones not coming back to transit  height within gravity field

**Comment by ManuelSchmitz** [comment]
If fixed, I am gonna merge the patch.

Thank you for the offer. I can always use testers. Currently, I'd like mining in P-gravity with different drones being tested.

I do not have a Discord account, but I'll create on and add you. Just not today, because work. Looking forward!
